version: "3.8"


services:
  #? 実行Command: docker-compose up n8n
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
    environment:
      - TZ=Asia/Tokyo

  # dockerサービスの設定
  # ここで設定することでコンテナ内の配置や動作を指定できる
  #? 実行Command: docker compose run --rm python-app
  python-app:
    build: ./python-app
    working_dir: /app

    # 対象のファイルを指定して自動保存で常時同期状態にする
    volumes:
      - ./python-app:/app

    # コンテナ起動させる際のコマンドを指定
    command: ["/bin/bash"]
