version: '3'

services:
  n8n:
    image: n8nio/n8n

    # ここは外部公開するポート
    # 今回はChatwork連携ように仕様

    # ここにアクセスするとn8nのUIにアクセスできてフローを作成できる
    ports:
      - "5678:5678"

    # n8n用の永続データをホスト側のホームディレクトリに保存
    volumes:
      - ~/.n8n:/home/node/.n8n


    # n8n の基本設定（環境変数）
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678

    # 自動再起動（落ちても勝手に復活）
    restart: unless-stopped

  python-service:
    build: ./python-service
    container_name: python-chatwork-bot
    ports:
      - "8000:8000"
