version: "3.8"


services:
  #? 実行Command: docker-compose up n8n
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
    environment:
      - TZ=Asia/Tokyo

  #? 実行Command: docker compose run --rm python-app
  python-app:
    build: ./python-app
    working_dir: /app
    volumes:
      - ./python-app:/app
    command: ["/bin/bash"]
